### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by carlosm-silva** [EnormousApplePie/Lekmod#6]
Hello! I'm a great fan of Civilization V, Lekmod, and the No Quitters group. I'm from Brazil, therefore native in Portuguese and fluent in English, as I've been living in the US for a while now. I would be willing to translate Lekmod, in parts or its entirety to Portuguese.

I'm aware that Portuguese was not originally included as a base Language in Civilization V. Still, I believe one could work on top of other language repositories, such as https://github.com/Anpix/Civ5-PTBR , to make it possible.

I'm open to any questions and suggestions. Hope you have a nice day :)

**Comment by BERaleks** [comment]
Hi, were you able to make a translation? I want to try to translate this mod into Russian for users from CIS countries.
