### ISSUE TITLE
No discussion on why not to have a tracked .gitignore file

### ISSUE THREAD

**Issue by Mandritti** [EnormousApplePie/Lekmod#8]
Hereby a suggestion:  Discuss maintaining .gitignore in the repository toplevel.

I saw that a .gitignore at one point in the last year was in the repository, but it is removed.  There is no stated policy, so I'd like to know if I can add one.

**Comment by LeM0-Dev** [comment]
@Mandritti [VisualStudio.gitignore](https://github.com/EnormousApplePie/Lekmod/blob/main/VisualStudio.gitignore) it exists
